# Generated by Django 6.0.3 on 2026-03-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('compressed_file', models.FileField(blank=True, null=True, upload_to='compressed/')),
                ('original_size_kb', models.FloatField(default=0)),
                ('compressed_size_kb', models.FloatField(blank=True, default=0, null=True)),
                ('target_size_kb', models.IntegerField(default=500)),
                ('reduction_percent', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
